export {default as Header} from "./header/Header"
export {default as Footer} from "./footer/Footer"
export {default as Nav} from "./nav/Nav"
export {default as HeroSection} from "./heroSection/HeroSection"
export {default as Offer} from "./offer/Offer"
export {default as Membership} from "./membership/Membership"
export {default as Review} from "./review/Review"
export {default as Started} from "./stated/Started"
